### ISSUE TITLE
Todo 2/10/2017

### ISSUE THREAD

**Issue by slin63** [slin63/InitiumCopy#1]
- Scenes
 - [ ] Add weather attribute
  - [ ] Weather only changes every `x` minutes instead of upon visiting each instance
    - Might be a `PITA` to do
  - [ ] Certain scenes have a higher propensity to certain weather conditions
  - [ ] Weather changes bonuses
  - [ ] Weather descriptions
 - [ ] Weather generator function
  - [ ] Generates a large set of scenes to test random generation
